# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

neighbourhood <- function(n, m, x, ndist, wdist, state) {
    .Call('FoxSim_neighbourhood', PACKAGE = 'FoxSim', n, m, x, ndist, wdist, state)
}

matchspatial <- function(n, m, y, x, ncells, state) {
    .Call('FoxSim_matchspatial', PACKAGE = 'FoxSim', n, m, y, x, ncells, state)
}

foxsim <- function(nr, nc, ksize, x, roads, incpoints, Kern, parms) {
    .Call('FoxSim_foxsim', PACKAGE = 'FoxSim', nr, nc, ksize, x, roads, incpoints, Kern, parms)
}

foxscatsim <- function(nr, nc, ksize, x, roads, incpoints, Kern, parms) {
    .Call('FoxSim_foxscatsim', PACKAGE = 'FoxSim', nr, nc, ksize, x, roads, incpoints, Kern, parms)
}

