# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

neighbourhood <- function(x, wdist, state) {
    .Call('FoxSim_neighbourhood', PACKAGE = 'FoxSim', x, wdist, state)
}

matchspatial <- function(locs, x, ncells, state) {
    .Call('FoxSim_matchspatial', PACKAGE = 'FoxSim', locs, x, ncells, state)
}

foxsim <- function(x, roads, incpoints, Kern, baitlist, parms) {
    .Call('FoxSim_foxsim', PACKAGE = 'FoxSim', x, roads, incpoints, Kern, baitlist, parms)
}

